/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_A9263EE7__
#define __PLUGINEDITOR_H_A9263EE7__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class ConvergenceVstAudioProcessorEditor  : public AudioProcessorEditor,
                                            public Button::Listener,
                                            public Slider::Listener
{
public:
    ConvergenceVstAudioProcessorEditor (ConvergenceVstAudioProcessor* ownerFilter);
    ~ConvergenceVstAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    void buttonClicked (Button *button);
    void sliderValueChanged (Slider *slider);
    
private:
    ScopedPointer<TextButton>generateText;
    ScopedPointer<Slider> tweetUpdateInterval;
};


#endif  // __PLUGINEDITOR_H_A9263EE7__
